function [ ] = reassignCurrentROI( minCoords,maxCoords )
%REASSIGNCURRENTROI Summary of this function goes here
%   Detailed explanation goes here

baselineScan = evalin('base','baselineScan');
assignin('base','currentBaseROI',baselineScan(...
        minCoords(1):maxCoords(1),...
        minCoords(2):maxCoords(2),...
        minCoords(3):maxCoords(3)));
try
    comparisonScan = evalin('base','comparisonScan');
    assignin('base','currentComparisonROI',...
        comparisonScan(...
        minCoords(1):maxCoords(1),...
        minCoords(2):maxCoords(2),...
        minCoords(3):maxCoords(3)));
catch 
end

end

